import { FriendProfile, UserGiverProgress } from '../types';

export const INITIAL_PROFILES: FriendProfile[] = [
  {
    id: 'friend-chloe',
    name: 'Chloe Miller',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=300',
    relationship: 'Bestie',
    birthday: '2008-08-14',
    zodiacSign: 'Leo ♌️',
    bio: 'Matcha obsessed, film camera collector & sunset lover ✨',
    theme: {
      color: '#FDF2F4', // Soft Blush Pink
      accentColor: '#FB7185',
      pattern: 'y2k-hearts',
      unlocked: true,
    },
    preferences: {
      favoriteColors: ['Sage Green', 'Soft Pink', 'Butter Yellow'],
      favoriteSnacks: ['Dried Mango from TJ\'s', 'Matcha Pocky', 'Baked Jalapeño Chips'],
      favoriteDrinks: ['Iced Matcha Oat Latte', 'Strawberry Guava Boba (50% sweet)'],
      favoriteShops: ['Glossier', 'Sephora', 'Brandy Melville', 'Lululemon', 'Jellycat'],
      favoriteFlowers: ['Peonies', 'Pink Tulips', 'Baby\'s Breath'],
      clothingSize: 'Top: Small | Pants: 26 / 2',
      shoeSize: '7.5 US Womens',
      jewellery: {
        metal: '14k Gold strictly (no silver/tarnish)',
        style: 'Dainty huggie hoops, thin stacked rings, pearl pendants',
      },
      allergies: ['Peanuts (mild)', 'Synthetic perfumed lotion (sensitive skin)'],
      doNotWant: [
        'NO scented body sprays or bath bombs',
        'NO silver jewellery',
        'NO dark lipstick or heavy makeup',
        'NO fast fashion polyester sweaters',
      ],
      hobbies: ['Pilates', 'Film photography', 'Baking matcha cookies', 'Thriting'],
    },
    notes: [
      {
        id: 'note-1',
        content: 'Mentioned in Sephora last Tuesday that she ran out of Sol De Janeiro Cheirosa 68 body mist! 🌸',
        dateAdded: '3 days ago',
        authorName: 'Sophia',
      },
      {
        id: 'note-2',
        content: 'Saw a cute Jellycat croissant bag at Nordstrom and said "omg I need this for my birthday!" 🥐',
        dateAdded: '1 week ago',
        authorName: 'Sophia',
      },
    ],
    wishlistItems: [
      {
        id: 'wish-1',
        title: 'Sol De Janeiro Cheirosa 68 Beija Flor Perfume Mist (240ml)',
        price: 38,
        priceRangeTag: '35to75',
        store: 'Sephora',
        url: 'https://sephora.com',
        imageUrl: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&q=80&w=400',
        category: 'Beauty',
        claimedBy: 'Sophia',
        claimedStatus: 'claimed',
        priority: 'high',
        notes: 'Her ultimate daily scent!',
      },
      {
        id: 'wish-2',
        title: 'Jellycat Amuseable Croissant Plush Shoulder Bag',
        price: 35,
        priceRangeTag: '15to35',
        store: 'Nordstrom / Jellycat',
        url: 'https://jellycat.com',
        imageUrl: 'https://images.unsplash.com/photo-1559563458-527698bf5295?auto=format&fit=crop&q=80&w=400',
        category: 'Accessories',
        claimedBy: null,
        claimedStatus: 'unclaimed',
        priority: 'high',
        notes: 'So cute for coffee runs',
      },
      {
        id: 'wish-3',
        title: '14k Gold Plated Dainty Pearl Huggie Earrings',
        price: 24,
        priceRangeTag: '15to35',
        store: 'Etsy / Mejuri',
        url: 'https://mejuri.com',
        imageUrl: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&q=80&w=400',
        category: 'Jewelry',
        claimedBy: null,
        claimedStatus: 'chipping_in',
        chipInCount: 2,
        priority: 'medium',
        notes: 'Chipping in with Mia ($12 each)!',
      },
      {
        id: 'wish-4',
        title: 'Lululemon Everywhere Belt Bag (Pastel Pink)',
        price: 38,
        priceRangeTag: '35to75',
        store: 'Lululemon',
        url: 'https://lululemon.com',
        imageUrl: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&q=80&w=400',
        category: 'Fashion',
        claimedBy: null,
        claimedStatus: 'unclaimed',
        priority: 'medium',
      },
      {
        id: 'wish-5',
        title: 'Kodak Ektar H35 Half Frame Reusable Film Camera (Sage Green)',
        price: 65,
        priceRangeTag: '35to75',
        store: 'Urban Outfitters',
        url: 'https://urbanoutfitters.com',
        imageUrl: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&q=80&w=400',
        category: 'Gadgets & Fun',
        claimedBy: null,
        claimedStatus: 'unclaimed',
        priority: 'high',
      },
    ],
    dreamBoardItems: [
      {
        id: 'db-1',
        title: 'Pastel Matcha Bar & Room Corner Aesthetic',
        type: 'photo',
        mediaUrl: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&q=80&w=500',
        price: 18,
        priceRangeTag: '15to35',
        boardCategory: 'Room & Cozy',
        notes: 'Love the cute glass matcha whisk jar',
      },
      {
        id: 'db-2',
        title: 'TikTok Viral Bow Claw Clips Pack',
        type: 'tiktok_idea',
        mediaUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&q=80&w=500',
        price: 12,
        priceRangeTag: 'under15',
        boardCategory: 'Beauty & Glow',
        notes: 'Stocking stuffer idea!',
      },
      {
        id: 'db-3',
        title: 'Dainty Gold Heart Choker Necklace',
        type: 'photo',
        mediaUrl: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&q=80&w=500',
        price: 45,
        priceRangeTag: '35to75',
        boardCategory: 'Jewelry & Sparkle',
      },
    ],
    reminderEnabled: true,
    reminderDaysBefore: 14,
  },
  {
    id: 'friend-maya',
    name: 'Maya Patel',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=300',
    relationship: 'Sister',
    birthday: '2009-09-28',
    zodiacSign: 'Libra ♎️',
    bio: 'Book lover, cozy sweater enthusiast & espresso martini baker ☕️',
    theme: {
      color: '#F3E8FF', // Lavender / Soft Lilac
      accentColor: '#A855F7',
      pattern: 'starry-sky',
      unlocked: true,
    },
    preferences: {
      favoriteColors: ['Lavender', 'Cream / Vanilla', 'Mocha Brown'],
      favoriteSnacks: ['Chocolove Almond Sea Salt Dark Chocolate', 'Cinnamon Almonds', 'Trader Joe\'s Peanut Butter Cups'],
      favoriteDrinks: ['Iced Oat Vanilla Latte', 'Chai Tea Latte with Oat Milk'],
      favoriteShops: ['Anthro / Anthropologie', 'Aritzia', 'Barnes & Noble', 'Mejuri', 'Target'],
      favoriteFlowers: ['White Hydrangeas', 'Lavender Bunches'],
      clothingSize: 'Top: XS | Pants: 24 / 00',
      shoeSize: '6.5 US Womens',
      jewellery: {
        metal: 'Silver & White Gold',
        style: 'Minimalist sterling silver cuffs, chunky silver hoops, crystal drops',
      },
      allergies: ['Lactose (prefers oat milk / dairy free chocolate)'],
      doNotWant: [
        'NO yellow gold jewelry',
        'NO neon colored clothes',
        'NO heavy floral perfume (gets migraines)',
      ],
      hobbies: ['Reading romance & fantasy novels', 'Baking sourdough & cinnamon buns', 'Journaling'],
    },
    notes: [
      {
        id: 'note-3',
        content: 'Wants the special collector edition of Fourth Wing book! 📚',
        dateAdded: '2 weeks ago',
        authorName: 'Sophia',
      },
    ],
    wishlistItems: [
      {
        id: 'wish-6',
        title: 'Anthropologie Bistro Tile Monogram Mug',
        price: 14,
        priceRangeTag: 'under15',
        store: 'Anthropologie',
        url: 'https://anthropologie.com',
        imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=400',
        category: 'Room & Home',
        claimedBy: null,
        claimedStatus: 'unclaimed',
        priority: 'high',
      },
      {
        id: 'wish-7',
        title: 'Sterling Silver Chunky Twisted Hoop Earrings',
        price: 32,
        priceRangeTag: '15to35',
        store: 'Mejuri',
        url: 'https://mejuri.com',
        imageUrl: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&q=80&w=400',
        category: 'Jewelry',
        claimedBy: 'Sophia',
        claimedStatus: 'claimed',
        priority: 'high',
      },
      {
        id: 'wish-8',
        title: 'Kindle Paperwhite Leather Cover (Lavender Lilac)',
        price: 29,
        priceRangeTag: '15to35',
        store: 'Amazon',
        url: 'https://amazon.com',
        imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=400',
        category: 'Tech',
        claimedBy: null,
        claimedStatus: 'unclaimed',
        priority: 'medium',
      },
    ],
    dreamBoardItems: [
      {
        id: 'db-4',
        title: 'Cozy Reading Nook Throw Blanket in Cream',
        type: 'photo',
        mediaUrl: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&q=80&w=500',
        price: 40,
        priceRangeTag: '35to75',
        boardCategory: 'Room & Cozy',
      },
    ],
    reminderEnabled: true,
    reminderDaysBefore: 14,
  },
  {
    id: 'friend-emma',
    name: 'Emma Watson',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=300',
    relationship: 'Partner',
    birthday: '2007-11-03',
    zodiacSign: 'Scorpio ♏️',
    bio: 'Sneakerhead, vinyl records collector & thrift icon 🎧',
    theme: {
      color: '#ECFDF5', // Soft Mint
      accentColor: '#10B981',
      pattern: 'pastel-waves',
      unlocked: true,
    },
    preferences: {
      favoriteColors: ['Forest Green', 'Cream', 'Charcoal Grey'],
      favoriteSnacks: ['Sour Patch Kids Watermelon', 'Pringles Sour Cream', 'Takis Nitro'],
      favoriteDrinks: ['Iced Matcha Latte with Vanilla Cold Foam', 'Poppi Soda (Raspberry Rose)'],
      favoriteShops: ['Princess Polly', 'Nike', 'Urban Outfitters', 'Glossier', 'PacSun'],
      favoriteFlowers: ['Sunflowers', 'Eucalyptus branches'],
      clothingSize: 'Top: Medium | Pants: 28 / 6',
      shoeSize: '8.0 US Womens (or 6.5 Mens)',
      jewellery: {
        metal: 'Mix of Gold & Silver',
        style: 'Chunky rings, chain bracelets, layered pendants',
      },
      allergies: ['Shellfish'],
      doNotWant: [
        'NO super girly lace frills',
        'NO heels',
        'NO plastic water bottles',
      ],
      hobbies: ['Collecting vinyl records', 'Skateboarding', 'Thrifting baggy denim'],
    },
    notes: [
      {
        id: 'note-4',
        content: 'Loved the Frank Ocean Blonde vinyl record replica when we passed the record shop! 🎵',
        dateAdded: 'Yesterday',
        authorName: 'Sophia',
      },
    ],
    wishlistItems: [
      {
        id: 'wish-9',
        title: 'Nike Dunk Low Sneaker (Cacao Wow / Cream)',
        price: 115,
        priceRangeTag: 'splurge75',
        store: 'Nike / GOAT',
        url: 'https://nike.com',
        imageUrl: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&q=80&w=400',
        category: 'Fashion & Shoes',
        claimedBy: null,
        claimedStatus: 'chipping_in',
        chipInCount: 3,
        priority: 'high',
        notes: 'Group gift chip-in with her roommates!',
      },
      {
        id: 'wish-10',
        title: 'Glossier You Eau de Parfum (Rollerball 8ml)',
        price: 32,
        priceRangeTag: '15to35',
        store: 'Glossier / Sephora',
        url: 'https://glossier.com',
        imageUrl: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&q=80&w=400',
        category: 'Beauty',
        claimedBy: 'Sophia',
        claimedStatus: 'claimed',
        priority: 'high',
      },
    ],
    dreamBoardItems: [
      {
        id: 'db-5',
        title: 'Retro Portable Record Player in Sage Green',
        type: 'photo',
        mediaUrl: 'https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&q=80&w=500',
        price: 85,
        priceRangeTag: 'splurge75',
        boardCategory: 'Room & Cozy',
      },
    ],
    reminderEnabled: true,
    reminderDaysBefore: 14,
  },
  {
    id: 'friend-lily',
    name: 'Lily Thorne',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&q=80&w=300',
    relationship: 'Friend',
    birthday: '2008-04-19',
    zodiacSign: 'Aries ♈️',
    bio: 'Balletcore, ribbon ribbons everywhere & strawberry sweet 🍓',
    theme: {
      color: '#FEFCE8', // Buttercream
      accentColor: '#EAB308',
      pattern: 'cherry-blossom',
      unlocked: true,
    },
    preferences: {
      favoriteColors: ['Butter Yellow', 'Baby Pink', 'White Lace'],
      favoriteSnacks: ['Macarons', 'Strawberry Pocky', 'Trader Joe\'s Mochi'],
      favoriteDrinks: ['Iced Strawberry Latte', 'Peach Jasmine Tea'],
      favoriteShops: ['LoveShackFancy', 'Skims', 'Zara', 'Sephora'],
      favoriteFlowers: ['Ranunculus', 'Pink Roses', 'Cherry Blossoms'],
      clothingSize: 'Top: Small | Pants: 25 / 1',
      shoeSize: '7.0 US Womens',
      jewellery: {
        metal: 'Rose Gold & Pearls',
        style: 'Ribbon bow motif rings, pearl studs, delicate wristlet charms',
      },
      allergies: ['Gluten (prefers gluten-free bakery treats)'],
      doNotWant: [
        'NO chunky black goth jewellery',
        'NO spicy snacks',
      ],
      hobbies: ['Pilates', 'Ballet', 'Making charm bracelets'],
    },
    notes: [],
    wishlistItems: [
      {
        id: 'wish-11',
        title: 'SKIMS Fits Everybody Soft Cami in Cherry Blossom',
        price: 38,
        priceRangeTag: '35to75',
        store: 'SKIMS',
        url: 'https://skims.com',
        imageUrl: 'https://images.unsplash.com/photo-1583846783214-7229a91b20ed?auto=format&fit=crop&q=80&w=400',
        category: 'Fashion',
        claimedBy: null,
        claimedStatus: 'unclaimed',
        priority: 'high',
      },
    ],
    dreamBoardItems: [],
    reminderEnabled: true,
    reminderDaysBefore: 7,
  },
];

export const INITIAL_USER_PROGRESS: UserGiverProgress = {
  giverLevel: 3,
  giftsGivenCount: 5,
  unlockedThemes: ['solid', 'glitter', 'y2k-hearts', 'pastel-waves', 'starry-sky', 'cherry-blossom'],
  badges: [
    {
      id: 'badge-1',
      name: 'Thoughtful Bestie',
      icon: '💖',
      description: 'Added preferences and DO NOT WANT list for 3 friends',
      unlockedAt: '2026-06-10',
    },
    {
      id: 'badge-2',
      name: 'Birthday Countdown Queen',
      icon: '👑',
      description: 'Set reminders for all upcoming birthdays',
      unlockedAt: '2026-06-15',
    },
    {
      id: 'badge-3',
      name: 'Gift Genie Master',
      icon: '🎁',
      description: 'Reserved/Claimed 3 gifts and prevented duplicate surprises!',
      unlockedAt: '2026-07-01',
    },
  ],
};
